In [19]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [20]:
df = pd.read_csv('user_tweets_from.csv', header=None)
df.columns = ['tweet_id','created_at','favorite_count','retweet_count','followers_count','screen_name','industry']
df.set_index('tweet_id', inplace=True)

# feature processing
df['RFR'] = (df['favorite_count']+df['retweet_count'])/df['followers_count']

In [21]:
df.head()

,created_at,favorite_count,retweet_count,followers_count,screen_name,industry,RFR
tweet_id,,,,,,,
981598371935797248,2018-04-04 18:24:23,3693,466,12763228,TheRock,celebrity,0.000326
981587805028605952,2018-04-04 17:42:24,0,48,12763228,TheRock,celebrity,0.000004
981587495530844160,2018-04-04 17:41:10,0,9747,12763228,TheRock,celebrity,0.000764
981566847035195392,2018-04-04 16:19:07,1206,103,12763228,TheRock,celebrity,0.000103
981566122741833728,2018-04-04 16:16:14,1283,98,12763228,TheRock,celebrity,0.000108

In [54]:
# normalization
def normalize(df):
    result = df.copy()
    for feature_name in df.columns:
        print(type(df[feature_name].iloc[0]))
        if (type(df[feature_name].iloc[0]) == numpy.int) | (type(df[feature_name].iloc[0]) == numpy.float):
            max_value = df[feature_name].max()
            min_value = df[feature_name].min()
            result[feature_name] = (df[feature_name] - min_value) / (max_value - min_value)
    return result

In [55]:
t = normalize(df)

<class 'str'>

NameError: name 'numpy' is not defined

In [53]:
t

,created_at,favorite_count,retweet_count,followers_count,screen_name,industry,RFR
tweet_id,,,,,,,
981598371935797248,2018-04-04 18:24:23,3693,466,12763228,TheRock,celebrity,0.000326
981587805028605952,2018-04-04 17:42:24,0,48,12763228,TheRock,celebrity,0.000004
981587495530844160,2018-04-04 17:41:10,0,9747,12763228,TheRock,celebrity,0.000764
981566847035195392,2018-04-04 16:19:07,1206,103,12763228,TheRock,celebrity,0.000103
981566122741833728,2018-04-04 16:16:14,1283,98,12763228,TheRock,celebrity,0.000108
981565509010272258,2018-04-04 16:13:48,38,3,12763228,TheRock,celebrity,0.000003
981565039395053570,2018-04-04 16:11:56,196,23,12763228,TheRock,celebrity,0.000017
981562299231031296,2018-04-04 16:01:03,5606,523,12763228,TheRock,celebrity,0.000480
981557502222348293,2018-04-04 15:41:59,0,102,12763228,TheRock,celebrity,0.000008
981557445515296768,2018-04-04 15:41:46,0,47,12763228,TheRock,celebrity,0.000004
981517857178570752,2018-04-04 13:04:27,8430,894,12763228,TheRock,celebrity,0.000731
981390853389406209,2018-04-04 04:39:47,2620,222,12763228,TheRock,celebrity,0.000223
981388337209593856,2018-04-04 04:29:47,3060,236,12763228,TheRock,celebrity,0.000258
981304846971097088,2018-04-03 22:58:01,2115,227,12763228,TheRock,celebrity,0.000183
981279790534557696,2018-04-03 21:18:28,351,31,12763228,TheRock,celebrity,0.000030
981279645575168000,2018-04-03 21:17:53,0,203,12763228,TheRock,celebrity,0.000016
981276183705759744,2018-04-03 21:04:08,8580,1349,12763228,TheRock,celebrity,0.000778
981275604233408512,2018-04-03 21:01:49,1572,155,12763228,TheRock,celebrity,0.000135
981259757234266112,2018-04-03 19:58:51,2790,247,12763228,TheRock,celebrity,0.000238
981214779481104385,2018-04-03 17:00:08,2707,265,12763228,TheRock,celebrity,0.000233
981212359690567680,2018-04-03 16:50:31,0,611,12763228,TheRock,celebrity,0.000048
980678769433239552,2018-04-02 05:30:13,100667,25741,12763228,TheRock,celebrity,0.009904
980667412134608897,2018-04-02 04:45:05,53541,9791,12763228,TheRock,celebrity,0.004962
980665781225627648,2018-04-02 04:38:36,20218,2473,12763228,TheRock,celebrity,0.001778
980659666324606976,2018-04-02 04:14:18,4888,1007,12763228,TheRock,celebrity,0.000462
980655988943433728,2018-04-02 03:59:42,31,4,12763228,TheRock,celebrity,0.000003
980630145558986753,2018-04-02 02:17:00,1418,175,12763228,TheRock,celebrity,0.000125
980629109721067520,2018-04-02 02:12:53,2324,217,12763228,TheRock,celebrity,0.000199
980627812783550465,2018-04-02 02:07:44,2081,146,12763228,TheRock,celebrity,0.000174
980624270060503042,2018-04-02 01:53:39,4580,424,12763228,TheRock,celebrity,0.000392
...,...,...,...,...,...,...,...
947565920225935360,2017-12-31 20:31:34,639,109,4197671,Fergie,musician,0.000178
946900830866644992,2017-12-30 00:28:45,2829,304,4197671,Fergie,musician,0.000746
946568246827745280,2017-12-29 02:27:11,861,181,4197671,Fergie,musician,0.000248
946503216077918208,2017-12-28 22:08:46,2176,225,4197671,Fergie,musician,0.000572
946480449404178433,2017-12-28 20:38:18,734,115,4197671,Fergie,musician,0.000202
945727705408040960,2017-12-26 18:47:10,0,126,4197671,Fergie,musician,0.000030
945168373083721728,2017-12-25 05:44:35,1354,275,4197671,Fergie,musician,0.000388
945164664941539328,2017-12-25 05:29:51,1111,128,4197671,Fergie,musician,0.000295
945114072902721537,2017-12-25 02:08:49,2844,261,4197671,Fergie,musician,0.000740
944096962105696256,2017-12-22 06:47:10,741,102,4197671,Fergie,musician,0.000201
944033609819631621,2017-12-22 02:35:26,2074,238,4197671,Fergie,musician,0.000551
942249314277036032,2017-12-17 04:25:17,1592,302,4197671,Fergie,musician,0.000451
942212540561489926,2017-12-17 01:59:09,820,188,4197671,Fergie,musician,0.000240
942148351352627200,2017-12-16 21:44:05,371,63,4197671,Fergie,musician,0.000103
941521471041687552,2017-12-15 04:13:05,352,62,4197671,Fergie,musician,0.000099
941519237084057600,2017-12-15 04:04:13,0,89,4197671,Fergie,musician,0.000021
941519003025059840,2017-12-15 04:03:17,732,115,4197671,Fergie,musician,0.000202
941517135108608000,2017-12-15 03:55:52,32,10,4197671,Fergie,musician,0.000010
941426509784408064,2017-12-14 21:55:45,1132,269,4197671,Fergie,musician,0.000334
941370253639946241,2017-12-14 18:12:12,990,158,4197671,Fergie,musician,0.000273
941307030563885057,2017-12-14 14:00:59,0,27,4197671,Fergie,musician,0.000006
941295174730338304,2017-12-14 13:13:52,539,83,4197671,Fergie,musician,0.000148
941083717703028742,2017-12-13 23:13:37,3525,398,4197671,Fergie,musician,0.000935
940083678922682368,2017-12-11 04:59:49,1695,253,4197671,Fergie,musician,0.000464
939979244154654720,2017-12-10 22:04:50,2576,349,4197671,Fergie,musician,0.000697
939673569843220480,2017-12-10 01:50:11,9,0,4197671,Fergie,musician,0.000002
939656683558711301,2017-12-10 00:43:05,2490,340,4197671,Fergie,musician,0.000674
939656624888786944,2017-12-10 00:42:52,0,117,4197671,Fergie,musician,0.000028
938878884883316737,2017-12-07 21:12:24,0,88,4197671,Fergie,musician,0.000021
938878870496755712,2017-12-07 21:12:20,0,69,4197671,Fergie,musician,0.000016

tweet_id
981598371935797248    2018-04-04 18:24:23
981587805028605952    2018-04-04 17:42:24
981587495530844160    2018-04-04 17:41:10
981566847035195392    2018-04-04 16:19:07
981566122741833728    2018-04-04 16:16:14
981565509010272258    2018-04-04 16:13:48
981565039395053570    2018-04-04 16:11:56
981562299231031296    2018-04-04 16:01:03
981557502222348293    2018-04-04 15:41:59
981557445515296768    2018-04-04 15:41:46
981517857178570752    2018-04-04 13:04:27
981390853389406209    2018-04-04 04:39:47
981388337209593856    2018-04-04 04:29:47
981304846971097088    2018-04-03 22:58:01
981279790534557696    2018-04-03 21:18:28
981279645575168000    2018-04-03 21:17:53
981276183705759744    2018-04-03 21:04:08
981275604233408512    2018-04-03 21:01:49
981259757234266112    2018-04-03 19:58:51
981214779481104385    2018-04-03 17:00:08
981212359690567680    2018-04-03 16:50:31
980678769433239552    2018-04-02 05:30:13
980667412134608897    2018-04-02 04:45:05
980665781225627648    2018-04-02 04:38:36
980659666324606976    2018-04-02 04:14:18
980655988943433728    2018-04-02 03:59:42
980630145558986753    2018-04-02 02:17:00
980629109721067520    2018-04-02 02:12:53
980627812783550465    2018-04-02 02:07:44
980624270060503042    2018-04-02 01:53:39
                             ...
947565920225935360    2017-12-31 20:31:34
946900830866644992    2017-12-30 00:28:45
946568246827745280    2017-12-29 02:27:11
946503216077918208    2017-12-28 22:08:46
946480449404178433    2017-12-28 20:38:18
945727705408040960    2017-12-26 18:47:10
945168373083721728    2017-12-25 05:44:35
945164664941539328    2017-12-25 05:29:51
945114072902721537    2017-12-25 02:08:49
944096962105696256    2017-12-22 06:47:10
944033609819631621    2017-12-22 02:35:26
942249314277036032    2017-12-17 04:25:17
942212540561489926    2017-12-17 01:59:09
942148351352627200    2017-12-16 21:44:05
941521471041687552    2017-12-15 04:13:05
941519237084057600    2017-12-15 04:04:13
941519003025059840    2017-12-15 04:03:17
941517135108608000    2017-12-15 03:55:52
941426509784408064    2017-12-14 21:55:45
941370253639946241    2017-12-14 18:12:12
941307030563885057    2017-12-14 14:00:59
941295174730338304    2017-12-14 13:13:52
941083717703028742    2017-12-13 23:13:37
940083678922682368    2017-12-11 04:59:49
939979244154654720    2017-12-10 22:04:50
939673569843220480    2017-12-10 01:50:11
939656683558711301    2017-12-10 00:43:05
939656624888786944    2017-12-10 00:42:52
938878884883316737    2017-12-07 21:12:24
938878870496755712    2017-12-07 21:12:20
Name: created_at, Length: 10405, dtype: object